const mongoose =require('mongoose');
const db = require('./models');
mongoose.Promise = global.Promise

mongoose.connect(
    process.env.MONGODB_URI || "mongodb://localhost/wines"
);
//  db = mongoose.connection
// db.on('error', err => {
// 	console.log(`There was an error connecting to the database: ${err}`)
// })
// db.once('open', () => {
// 	console.log(
// 		`You have successfully connected to your mongo database: ${MONGO_URL}`
// 	)
// })

var wineSeed = [
    {
        "name": "Bandol (Red)",
        "pronunciation": "ban-dul",
        "summary": "Bandol is a tiny appellation within Provence, France that is most famous for its rich, peppery, and meaty red wines made almost exclusively with Mourvèdre.",
        "primaryFlavors": ["Blackberry", "Dark Chocolate", "Game", "White Pepper", "Anise"],
        "sweetness": "Bone-dry",
        "body": "Full Body",
        "varietal": ["no data"],
        "tannin": "High Tannin",
        "acidity": "Medium Acidity",
        "alcohol": "13.5-15% ABV",
        "temp": "Room temperature",
        "glassType": "Oversized",
        "decant": "1 Hour",
        "ageability": "10+ years",
        "pairings": ["gamey meats", "venison", "buffalo", "stews"]
    },    
    {
        "name": "Banyuls",
        "pronunciation": "ban-yuhls",
        "summary": "One of France’s most important sweet, fortified Vin Doux Naturel wines made primarily of Grenache and/or Grenache Blanc grapes with 6 official styles.",
        "primaryFlavors": ["Stewed Strawberry", "Baked Prues", "Earth", "Dark Chocolate"],
        "sweetness": "Very Sweet",
        "body": "Full Body",
        "varietal": ["no data"],
        "tannin": "Medium-High Tannin",
        "acidity": "Medium Acidity",
        "alcohol": "Over 15% ABV",
        "temp": "Room Temperature",
        "glassType": "Dessert",
        "decant": "No",
        "ageability": "10+ years",
        "pairings": ["chocolate"]
    },    
    {
        "name": "Barolo",
        "pronunciation": "bar-ollo",
        "summary": "Piedmont’s most famous red wine is made with 100% Nebbiolo grapes. Its translucent brick-red color, deceptively light body, and floral aromas contrast its dense tannin structure.",
        "primaryFlavors": ["Raspberry", "Cherry", "Rose", "Tar", "Licorice"],
        "sweetness": "Bone Dry",
        "body": "Full Body",
        "varietal": ["no data"],
        "tannin": "High Tannin",
        "acidity": "High Acidity",
        "alcohol": "13.5-15% ABV",
        "temp": "Room Temperature",
        "glassType": "Aroma Collector",
        "decant": "1 Hour",
        "ageability": "10+ Years",
        "pairings": ["truffle", "risotto", "pasta", "charcuterie"]
    },    
    {
        "name": "Beaujolais",
        "pronunciation": "bo-shjo-lay",
        "summary": "A French region just south of Bourgogne that’s devoted to Gamay-based wines. Most Beaujolais are simple, rustic reds, but the 10 Crus offer exceptional quality.",
        "primaryFlavors": ["Pomegranate", "Blackberry Bramble", "Violet", "Potting Soil", "Banana"],
        "sweetness": "Dry",
        "body": "Medium-light Body",
        "varietal": ["no data"],
        "tannin": "Medium-low Tannin",
        "acidity": "Medium-high Acidity",
        "alcohol": "10-11.5% ABV",
        "temp": "55–60°F / 13–16°C",
        "glassType": "Aroma Collector",
        "decant": "No",
        "ageability": "5-10 Years",
        "pairings": ["beef", "pork", "chicken", "salmon"]
    },  
    {
        "name": "Bordeaux Blend (Red)",
        "pronunciation": "bore-doe",
        "summary": "A red blend that’s dominated by Cabernet Sauvignon and Merlot, along with several other grape varieties native to the Bordeaux region of France.",
        "primaryFlavors": ["Black Currant", "Black Cherry", "Graphite", "Chocolate", "Dried Herbs"],
        "sweetness": "Bone Dry",
        "body": "Full Body",
        "varietal": ["no data"],
        "tannin": "High Tannin",
        "acidity": "Medium Acidity",
        "alcohol": "13.5-15% ABV",
        "temp": "Room Temperature",
        "glassType": "Oversized",
        "decant": "1 Hour",
        "ageability": "10+ Years",
        "pairings": ["steak", "red meat"]
    }, 
    {
        "name": "Bordeaux Blend (White)",
        "pronunciation": "bore-doe",
        "summary": "A white blend that’s dominated by Sémillon and Sauvignon Blanc, along with other grape varieties that are native to the Bordeaux region of France.",
        "primaryFlavors": ["Grapefruit", "Gooseberry", "Lemon Curd", "Chamomile", "Lemongrass"],
        "sweetness": "Dry",
        "body": "Medium-light Bosy",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "Medium-high Acidity",
        "alcohol": "11.5-13.5% ABV",
        "temp": "45–55°F / 7–13°C",
        "glassType": "White",
        "decant": "No",
        "ageability": "10+ Years",
        "pairings": ["trout", "oysters", "mussels", "sushi"]
    },
    {
        "name": "Brunello di Montalcino",
        "pronunciation": "brun-nello dee mont-tall-cheeno",
        "summary": "Brunello di Montalcino is of Italy’s top regional red wines, first labeled as such in 1865 by Biondi-Santi. Wines are made with a special clone of Sangiovese.",
        "primaryFlavors": ["Cherry", "Plum", "New Leather", "Herbs", "Clay Pot"],
        "sweetness": "Bone Dry",
        "body": "Medium-full Body",
        "varietal": ["no data"],
        "tannin": "High Tannin",
        "acidity": "Medium-high Acidity",
        "alcohol": "13.5-15% ABV",
        "temp": "Room Temperature",
        "glassType": "Oversized",
        "decant": "1 Hour",
        "ageability": "10+ Years",
        "pairings": ["prosciutto", "pancetta", "coppa", "bresaola"]
    },
    {
        "name": "Cap Classique",
        "pronunciation": "kap klass-eek",
        "summary": "",
        "primaryFlavors": ["Lemon", "White Cherry", "Ginger", "Cream", "Brioche"],
        "sweetness": "Dry",
        "body": "Light Body",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "High Acidity",
        "alcohol": "10-11.5% ABV",
        "temp": "38–45°F / 3–7°C",
        "glassType": "Flute",
        "decant": "No",
        "ageability": "5-10 Years",
        "pairings": ["chicken", "pork"]
    },
    {
        "name": "Cava",
        "pronunciation": "kah-vah",
        "summary": "Cava is the premier sparkling of Spain. The wine uses a similar quality tier system to Champagne but champions several of Spain’s native grapes including Macabeu (Viura), Xarel-lo, and Parellada.",
        "primaryFlavors": ["Quince", "Lime", "Yellow Apple", "Chamomile", "Almond"],
        "sweetness": "Dry",
        "body": "Light Body",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "High Acidity",
        "alcohol": "10-11.5% ABV",
        "temp": "38–45°F / 3–7°C",
        "glassType": "Flute",
        "decant": "No",
        "ageability": "3-5 Years",
        "pairings": ["tapas", "paella", "red bean chili"]
    },
    {
        "name": "Chablis",
        "pronunciation": "sha-blee",
        "summary": "A wine region in northern Burgundy that is as close to Champagne as it is to Burgundy, producing a leaner style of Chardonnay generally with less oak use.",
        "primaryFlavors": ["Quince", "Starfruit", "Lime Peel", "White Flowers", "Chalk"],
        "sweetness": "Bone Dry",
        "body": "Light Body",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "Medium-high Acidity",
        "alcohol": "11.5-13.5% ABV",
        "temp": "45–55°F / 7–13°C",
        "glassType": "White",
        "decant": "No",
        "ageability": "10+ years",
        "pairings": ["oysters"]
    },
    {
        "name": "Champagne",
        "pronunciation": "sham-pain",
        "summary": "The most iconic sparkling wine in the world is a blend of grapes including Chardonnay, Pinot Noir, and Pinot Meunier. The most treasured Champagne wines age for a minimum of 3 years.",
        "primaryFlavors": ["Citrus", "Yellow Apple", "Cream", "Almond", "Toast"],
        "sweetness": "Dry",
        "body": "Light Body",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "High Acidity",
        "alcohol": "10-11.5% ABV",
        "temp": "38–45°F / 3–7°C",
        "glassType": "Flute",
        "decant": "No",
        "ageability": "10+ years",
        "pairings": ["salty food", "fried food"]
    },
    {
        "name": "Chianti",
        "pronunciation": "key-ahn-tee",
        "summary": "The world-renowned Tuscan, Sangiovese-based wine was originally sold in straw-wrapped bottles called Fiascos. Chianti wines have many classifications by region and aging regime.",
        "primaryFlavors": ["Cherry", "Plumb", "Tomato Leaf", "Leather", "Clay Pot"],
        "sweetness": "Bone Dry",
        "body": "Medium-full Body",
        "varietal": ["no data"],
        "tannin": "High Tannin",
        "acidity": "Medium-high Acidity",
        "alcohol": "11.5%-13.5% ABV",
        "temp": "60–68°F / 16–20°C",
        "glassType": "Universal",
        "decant": "30 minutes",
        "ageability": "5-10 Years",
        "pairings": ["tomato-based sauces", "spaghetti", "meatballs", "lasagna"]
    },
    {
        "name": "Crémant",
        "pronunciation": "krem-mont",
        "summary": "",
        "primaryFlavors": ["Lemon", "Peach", "White Cherry", "Almond", "Toast"],
        "sweetness": "Dry",
        "body": "Light Body",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "High Acidity",
        "alcohol": "10-11.5% ABV",
        "temp": "38–45°F / 3–7°C",
        "glassType": "Flute",
        "decant": "No",
        "ageability": "3-5 Years",
        "pairings": ["fried foods", "soft cheeses", "salty appetizers"]
    },
    {
        "name": "Franciacorta",
        "pronunciation": "fran-cha-kor-tah",
        "summary": "A regional sparkling wine from northern Italy. Made in several styles, using the same method and grapes as Champagne, with the addition of Pinot Blanc.",
        "primaryFlavors": ["Lemon", "Peach", "White Cherry", "Almond", "Toast"],
        "sweetness": "dry",
        "body": "Light Body",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "High Acidity",
        "alcohol": "10-11.5% ABV",
        "temp": "",
        "glassType": "Flute",
        "decant": "No",
        "ageability": "5-10 Years",
        "pairings": ["soft cheese", "ripened cheeses", "dried fruits", "roasted salted nuts"]
    },
    {
        "name": "Ice Wine",
        "pronunciation": "eye-ss whyne",
        "summary": "A sweet, late harvest wine that can only be made when grapes naturally freeze in the vineyard at a minimum -8°C/17.6°F. Popular varieties include Riesling, Vidal, and Cabernet Franc.",
        "primaryFlavors": ["Pineapple", "Lemon Curd", "Honneysuckle", "Apricot", "Lychee"],
        "sweetness": "Very Sweet",
        "body": "Medium-full Body",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "Medium-high Acidity",
        "alcohol": "10-11.5% ABV",
        "temp": "45–55°F / 7–13°C",
        "glassType": "Dessert",
        "decant": "No",
        "ageability": "3-5 Years",
        "pairings": ["fruity desserts", "cheesecake", "ice cream", "soft cheese", "pungent cheese"]
    },
    {
        "name": "Lambrusco",
        "pronunciation": "lam-broos-co",
        "summary": "A family of 8 closely related grape varieties native to Italy that are made into sparkling wines, ranging from delicately colored rosés to deeply colored reds.",
        "primaryFlavors": ["Strawberry", "Blackberry", "Rhubarb", "Hibiscus", "Potting Soil"],
        "sweetness": "Dry",
        "body": "Medium-light Body",
        "varietal": ["no data"],
        "tannin": "Medium Tannin",
        "acidity": "Medium-high Acidity",
        "alcohol": "10-11.5% ABV",
        "temp": "45–55°F / 7–13°C",
        "glassType": "Universal",
        "decant": "No",
        "ageability": "1-3 Years",
        "pairings": ["pizza", "burgers", "prosciutto di parma", "parmigiano-reggiano"]
    },
    {
        "name": "Madeira",
        "pronunciation": "ma-deer-uh",
        "summary": "Oxidized, fortified dessert wines from the Island of Madeira ranging in style from off-dry to sweet. Wines are incredibly stable and are known to age over 100 years.",
        "primaryFlavors": ["Burnt Caramel", "Walnut Oil", "Peach", "Hazelnut", "Orange Peel"],
        "sweetness": "Sweet",
        "body": "Full Body",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "Medium-high Acidity",
        "alcohol": "Over 15% ABV",
        "temp": "55–60°F / 13–16°C",
        "glassType": "Dessert",
        "decant": "No",
        "ageability": "10+ Years",
        "pairings": ["artichoke", "pea soup", "asparagus"]
    },
    {
        "name": "Marsala",
        "pronunciation": "mar-sal-uh",
        "summary": "Marsala is a fortified wine from Sicily commonly used in cooking to create rich, caramelized sauces but can also make fine sipping wines, ranging from dry to sweet.",
        "primaryFlavors": ["Stewed Apricot", "Vanilla", "Tamarind", "Brown Sugar", "Tobacco"],
        "sweetness": "Sweet",
        "body": "Full Body",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "Medium Acidity",
        "alcohol": "Over 15% ABV",
        "temp": "55–60°F / 13–16°C",
        "glassType": "Dessert",
        "decant": "No",
        "ageability": "10+ Years",
        "pairings": ["nuts", "charcuterie", "dried fruit", "firm cheeses"]
    },
    {
        "name": "Maury",
        "pronunciation": "mar-rhee",
        "summary": "An appellation for the production of vin doux naturel (fortified wine) in the southern Roussillon of France. Wines must be made with a minimum 75% Grenache noir, among others.",
        "primaryFlavors": ["Stewed Strawberry", "Baked Brune", "Baked Earth", "Ginger Snap", "Burnt Caramel"],
        "sweetness": "Very Sweet",
        "body": "Full Body",
        "varietal": ["no data"],
        "tannin": "Medium-High Tannin",
        "acidity": "Medium Acidity",
        "alcohol": "Over 15% ABV",
        "temp": "55–60°F / 13–16°C",
        "glassType": "Dessert",
        "decant": "30 Minutes",
        "ageability": "10+ Years",
        "pairings": ["dessert", "chocolate mousse", "cake", "foie gras", "prunes", "dates", "blue cheese"]
    },
    {
        "name": "Moscatel de Setúbal",
        "pronunciation": "moe-ska-tell deh seh-too-ball",
        "summary": "A rich and honeyed fortified dessert wine made primarily with Muscat of Alexandria grapes grown on the Setúbal peninsula in Southern Portugal.",
        "primaryFlavors": ["Mandarin Orange", "Grape", "Dried Apricot", "Honey", "Caramel"],
        "sweetness": "Very Sweet",
        "body": "Full Body",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "Medium Acidity",
        "alcohol": "Under 10% ABV",
        "temp": "55–60°F / 13–16°C",
        "glassType": "Dessert",
        "decant": "No",
        "ageability": "3-5 Years",
        "pairings": ["Portuguese cheeses", "gooey cheese", "Queijo de Ovelha", "caramel", "dessert"]
    },
    {
        "name": "Orange Wine",
        "pronunciation": "or-enj",
        "summary": "The name is a bit of a misnomer because this wine isn’t made with oranges, but rather white grapes that have been fermented on their skins, much like red wine.",
        "primaryFlavors": ["Bruised Apple", "Jackfruit", "Linseed Oil", "Juniper", "Honey"],
        "sweetness": "Bone Dry",
        "body": "Medium-full Body",
        "varietal": ["no data"],
        "tannin": "Medium Tannin",
        "acidity": "Medium-high Acidity",
        "alcohol": "11.5-13.5% ABV",
        "temp": "55–60°F / 13–16°C",
        "glassType": "Universal",
        "decant": "30 Minute",
        "ageability": "5-10 Years",
        "pairings": ["roasted meats", "sage", "rosemary"]
    },
    {
        "name": "Port",
        "pronunciation": "port",
        "summary": "Portugal’s flagship; an aged, sweet fortified wine that comes in a wide range of styles, largely based on ageing techniques. Commonly seen styles include Ruby and Tawny.",
        "primaryFlavors": ["Plum", "Dried Cherry", "Chocolate", "Raisin", "Cinnamon"],
        "sweetness": "Very Sweet",
        "body": "Full Body",
        "varietal": ["no data"],
        "tannin": "High Tannin",
        "acidity": "Medium-high Acidity",
        "alcohol": "Over 15% ABV",
        "temp": "55–60°F / 13–16°C",
        "glassType": "Dessert",
        "decant": "No",
        "ageability": "10+ Years",
        "pairings": ["blue cheese"]
    },
    {
        "name": "Port (White)",
        "pronunciation": "port",
        "summary": "The most important fortified sweet wine of Portugal is made in a range of styles including white, rosé, red and tawny, each with a unique taste profile.",
        "primaryFlavors": ["Spiced Pear", "Quince", "Almond", "Honey", "Vanilla"],
        "sweetness": "Very Sweet",
        "body": "Medium-full Body",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "Medium-high Acidity",
        "alcohol": "Over 15% ABV",
        "temp": "45–55°F / 7–13°C",
        "glassType": "Dessert",
        "decant": "No",
        "ageability": "10+ Years",
        "pairings": ["chocolate", "fruit tarts", "Stilton cheese"]
    },
    {
        "name": "Priorat",
        "pronunciation": "pree-or-raht",
        "summary": "A Spanish regional wine blend known largely for its full, dusty red wines made primarily from Grenache and Carignan. The best age a minimum of five years before release and some include Merlot and Cabernet Sauvignon for additional complexity.",
        "primaryFlavors": ["Black Cherry", "Plum", "Crushed Gravel", "Licorice", "Dark Chocolate"],
        "sweetness": "Dry",
        "body": "Medium-full Body",
        "varietal": ["no data"],
        "tannin": "High Tannin",
        "acidity": "Medium-high Acidity",
        "alcohol": "13.5-15% ABV",
        "temp": "Room Temperature",
        "glassType": "Oversized",
        "decant": "1 Hour",
        "ageability": "10+ Years",
        "pairings": ["grilled meats", "grilled vegetables"]
    },
    {
        "name": "Prosecco",
        "pronunciation": "pro-seh-co",
        "summary": "Italy’s most popular sparkling wine is created mostly in Veneto and Friuli-Venezia Giulia. The best Prosecco wines come from the smaller sub-region of Valdobiaddene.",
        "primaryFlavors": ["Green Apple", "Honeydew Melon", "Pear", "Lager", "Cream"],
        "sweetness": "Dry",
        "body": "Light Body",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "Medium-high Acidity",
        "alcohol": "11.5-13.5%",
        "temp": "38–45°F / 3–7°C",
        "glassType": "White",
        "decant": "No",
        "ageability": "1-3 Years",
        "pairings": ["antipasta", "cured meats", "almonds", "spicy Asian food"]
    },
    {
        "name": "Provence (Rosé)",
        "pronunciation": "rose-aye",
        "summary": "Rosé was once only thought of as fruity and cloying; these dry and mineral driven pink wines (that contain a plethora of grapes) have proven that rosé can be serious. Seriously delicious.",
        "primaryFlavors": ["Strawberry", "Honeydew Melon", "Rose Petal", "Celery", "Watermelon"],
        "sweetness": "Dry",
        "body": "Light Body",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "Medium Acidity",
        "alcohol": "11.5-13.5% ABV",
        "temp": "38–45°F / 3–7°C",
        "glassType": "White",
        "decant": "No",
        "ageability": "3-5 Years",
        "pairings": ["charcuterie", "salads", "light pastas", "fresh fruit", "potato", "pasta salads"]
    },
    {
        "name": "Rhône",
        "pronunciation": "roan",
        "summary": "GSM stands for Grenache, Syrah, and Mourvèdre – three important grapes grown in the Côtes du Rhône region of France. Today, this blend is produced throughout the world and is loved for its complex red fruit flavors and age-worthy potential.",
        "primaryFlavors": ["Raspberry", "Blackberry", "Rosemary", "Baking Spices", "Lavendar"],
        "sweetness": "Dry",
        "body": "Medium-full Body",
        "varietal": ["no data"],
        "tannin": "Medium-high Tannin",
        "acidity": "Medium Acidity",
        "alcohol": "13.5-15% ABV",
        "temp": "60–68°F / 16–20°C",
        "glassType": "Aroma Collector",
        "decant": "30 Minutes",
        "ageability": "10+ Years",
        "pairings": ["red pepper", "sage", "rosemary", "olives"]
    },
    {
        "name": "Rhône Blend (White)",
        "pronunciation": "roan",
        "summary": "The rare white wines of the Rhône Valley offer a terrific alternative for Chardonnay lovers. Wines are typically a blend of Marsanne and Roussanne with a little Viognier and Grenache Blanc thrown in.",
        "primaryFlavors": ["Meyer Lemon", "Apricot", "Beeswax", "Orange Zest", "Brioche"],
        "sweetness": "Dry",
        "body": "Medium-light Body",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "Medium-low Acidity",
        "alcohol": "13.5-15% ABV",
        "temp": "45–55°F / 7–13°C",
        "glassType": "White",
        "decant": "No",
        "ageability": "5-10 Years",
        "pairings": ["rich poultry", "rich fish", "roasted fruit", "fruit-based sauces"]
    },
    {
        "name": "Rioja",
        "pronunciation": "ree-oh-hah",
        "summary": "Spain’s most famous regional wine featuring Tempranillo grapes. Wines are known for their savory, dusty flavors and ability to age. Rioja is one of few European winemaking zones that enlists the use of American oak barrels.",
        "primaryFlavors": ["Cherry", "Plum", "Dill", "Vanilla", "Old Leather"],
        "sweetness": "Dry",
        "body": "Medium-full Body",
        "varietal": ["no data"],
        "tannin": "Medium-high Tannin",
        "acidity": "Medium-high Acidity",
        "alcohol": "13.5-15% ABV",
        "temp": "55–60°F / 13–16°C",
        "glassType": "Universal",
        "decant": "1 Hour",
        "ageability": "10+ Years",
        "pairings": ["lamb", "chorizo", "roasted pork", "roasted chicken"]
    },
    {
        "name": "Sancerre",
        "pronunciation": "san-serre",
        "summary": "A regional wine from the Loire Valley of central France. Wines are mostly Sauvignon Blanc (and very rarely: Pinot Noir). Sauvignon Blanc is exceptionally lean and textured from Sancerre’s chalky soils.",
        "primaryFlavors": ["Gooseberry", "Grapefruit", "Honeydew Melon", "Hay", "Flint"],
        "sweetness": "Dry",
        "body": "Light Body",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "High Acidity",
        "alcohol": "11.5-13.5% ABV",
        "temp": "45–55°F / 7–13°C",
        "glassType": "White",
        "decant": "No",
        "ageability": "3-5 Years",
        "pairings": ["goat cheese", "Oysters", "salad", "citrus"]
    },
    {
        "name": "Sauternais",
        "pronunciation": "sow-turn-aye",
        "summary": "A group of rare dessert wines from Bordeaux made with Sémillon, Sauvignon Blanc, and Muscadelle grapes infected with a special kind of rot called Botrytis cinerea that concentrates the grape sugars.",
        "primaryFlavors": ["Marmalade", "Apricot", "Quince", "Honey", "Ginger"],
        "sweetness": "Very Sweet",
        "body": "Full Body",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "Medium-high Acidity",
        "alcohol": "11.5-13.5% ABV",
        "temp": "45–55°F / 7–13°C",
        "glassType": "Dessert",
        "decant": "No",
        "ageability": "10+ Years",
        "pairings": ["wash-rind soft cheeses", "roquefort"]
    },
    {
        "name": "Sherry",
        "pronunciation": "share-ee",
        "summary": "The top fortified wine of Spain made primarily with Palomino grapes and extended oxidative aging. It’s available in a range of styles of bone dry to very sweet.",
        "primaryFlavors": ["Jackfruit", "Saline", "Preserved Lemon", "Brazil Nut", "Almond"],
        "sweetness": "Off-Dry",
        "body": "Medium-light Body",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "High Acidity",
        "alcohol": "Over 15% ABV",
        "temp": "55–60°F / 13–16°C",
        "glassType": "Dessert",
        "decant": "No",
        "ageability": "3-5 Years",
        "pairings": ["smoked fish", "fried fish", "grilled fish", "grilled vegetables", "barbecue ribs", "gooey cheeses"]
    },
    {
        "name": "Tokaji Aszú",
        "pronunciation": "toe-ki ah-tsu",
        "summary": "A notable Hungarian sweet wine made mostly of Furmint grapes that are affected by a special rot called Botrytis cinerea. The rot concentrates the grape’s sugars and adds distinct aromas of ginger and saffron.",
        "primaryFlavors": ["Tangerine", "Apricot", "Honey", "Ginger", "Marzipan"],
        "sweetness": "Very Sweet",
        "body": "Medium Body",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "High Acidity",
        "alcohol": "11.5-13.5% ABV",
        "temp": "45–55°F / 7–13°C",
        "glassType": "Dessert",
        "decant": "No",
        "ageability": "10+ Years",
        "pairings": ["foie gras", "blue cheese", "crème caramel"]
    },
    {
        "name": "Trento",
        "pronunciation": "tren-toe",
        "summary": "A regional sparkling wine from Northern Italy dedicated to making wines using the Champagne method. Chardonnay features prominently in these bubbly wines although you’ll occasionally find Pinot Noir, Pinot Blanc, or Pinot Meunier blended in.",
        "primaryFlavors": ["Citrus", "Yellow Apple", "White Cherry", "Almond", "Toast"],
        "sweetness": "Dry",
        "sparkling": "sparkling",
        "body": "Light Body",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "High Acidity",
        "alcohol": "10-11.5% ABV",
        "temp": "38–45°F / 3–7°C",
        "glassType": "Flute",
        "decant": "No",
        "ageability": "3-5 Years",
        "pairings": ["oysters", "seafood", "roast chicken", "risotto", "creamy pastas"]
    },
    {
        "name": "Txakoli (White)",
        "pronunciation": "chalk-olli",
        "summary": "A bone dry, slightly spritzy wine from Spain’s Basque Country, produced in three different regions from a host of grapes, most importantly Hondarrabi Zuri.",
        "primaryFlavors": ["Lime", "Green Strawberry", "Peony", "Dried Herbs", "Saline"],
        "sweetness": "Dry",
        "body": "Light Body",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "High Acidity",
        "alcohol": "Under 10% ABV",
        "temp": "38–45°F / 3–7°C",
        "glassType": "White",
        "decant": "No",
        "ageability": "3-5 Years",
        "pairings": ["raw seafood", "ceviches", "oysters,", "sushi"]
    },
    {
        "name": "Valpolicella",
        "pronunciation": "val-polla-chellah",
        "summary": "The region’s most famous wine, Amarone della Valpolicella, partially dries grapes to increase concentration in a process called appasimento. Corvina is the darling grape of the Valpo blend and known for its flavors of cherries and chocolate.",
        "primaryFlavors": ["Tart Cherry", "Cinnamon", "Chocolate", "Green Peppercorn", "Almond"],
        "sweetness": "Dry",
        "body": "Medium Body",
        "varietal": ["no data"],
        "tannin": "Medium-low Tannin",
        "acidity": "High Acidity",
        "alcohol": "11.5%-13.5% ABV",
        "temp": "55–60°F / 13–16°C",
        "glassType": "University",
        "decant": "30 Minutes",
        "ageability": "10+ Years",
        "pairings": ["burgers", "roast chicken", "braised meats", "steaks", "mushrooms", "aged cheeses"]
    },
    {
        "name": "Vin Jaune",
        "pronunciation": "vin joan",
        "summary": "A rare, oxidized French white with bizarrely unique aromas. Occassionally, you’ll find it used in cooking where it adds an indescrible nutty taste to classic French dishes.",
        "primaryFlavors": ["Turpentine", "Dried Pear", "Rose Candy", "Fennel", "Toffee Nut"],
        "sweetness": "Dry",
        "body": "Medium-full Body",
        "varietal": ["no data"],
        "tannin": "Medium-low Tannin",
        "acidity": "Medium-high Acidity",
        "alcohol": "Over 15% ABV",
        "temp": "45–55°F / 7–13°C",
        "glassType": "Dessert",
        "decant": "No",
        "ageability": "10+ Years",
        "pairings": ["pastries", "almond biscotti", "soft cheese", "funky cheese", "Taleggio"]
    },
    {
        "name": "Vin Santo",
        "pronunciation": "vin son-tow",
        "summary": "Vin Santo or “holy wine” is a rare dessert wine found mostly in Tuscany. The grapes are first dried on straw mats to concentrate the sugars and can take as long as 4 years to ferment.",
        "primaryFlavors": ["Perfume", "Dried Fig", "Raisin", "Almond", "Toffee"],
        "sweetness": "Very Sweet",
        "body": "Full Body",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "High Acidity",
        "alcohol": "13.5-15% ABV",
        "temp": "55–60°F / 13–16°C",
        "glassType": "Dessert",
        "decant": "No",
        "ageability": "5-10 Years",
        "pairings": ["biscotti"]
    },
    {
        "name": "Vinho Verde",
        "pronunciation": "vino verr-day",
        "summary": "A regional wine blend from Portugal offered in both white, rosé and red styles. The most popular style is a fun, fruity white that usually has a touch of spritz.",
        "primaryFlavors": ["Lemonade", "Pink Grapefruit", "Lime Zest", "Yellow Apple", "White Blossom"],
        "sweetness": "Dry",
        "body": "Light Body",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "High Acidity",
        "alcohol": "10-11.5% ABV",
        "temp": "38–45°F / 3–7°C",
        "glassType": "White",
        "decant": "No",
        "ageability": "1-3 Years",
        "pairings": ["fish tacos", "mango salsa", "ceviche", "sushi"]
    },
    {
        "name": "Vinsanto",
        "pronunciation": "vin-sahn-tow",
        "summary": "Confusingly, not Italy’s Vin Santo, Vinsanto is a Greek sweet wine made in a passito style (sun-dried grapes) and known mostly from Santorini where it’s made with Assyrtiko.",
        "primaryFlavors": ["Dried Apricot", "Cherry Syrup", "Roasted Pepper", "Caramel", "Bergamot"],
        "sweetness": "Very Sweet",
        "body": "Full Body",
        "varietal": ["no data"],
        "tannin": "Medium Tannin",
        "acidity": "Medium Acidity",
        "alcohol": "11.5-13.5% ABV",
        "temp": "55–60°F / 13–16°C",
        "glassType": "Dessert",
        "decant": "No",
        "ageability": "10+ Years",
        "pairings": ["nutty dessert", "baklava", "kataïfi tart"]
    },
    {
        "name": "Vouvray",
        "pronunciation": "voo-vray",
        "summary": "A regional wine from France’s Loire Valley dedicated to the production of wines from the Chenin Blanc grape; available in an array of styles from dry to sweet, and still to sparkling.",
        "primaryFlavors": ["Lemon", "Apricot", "Pear", "Honey", "Chamomile"],
        "sweetness": "Dry",
        "body": "Light Body",
        "varietal": ["no data"],
        "tannin": "Low to no Tannin",
        "acidity": "High Acidity",
        "alcohol": "10-11.5% ABV",
        "temp": "45–55°F / 7–13°C",
        "glassType": "White",
        "decant": "No",
        "ageability": "10+ Years",
        "pairings": ["cheese souffle", "white fish", "pork", "pastas"]
    },
    {
        "name": "Allegrini Palazzo Della Torre - Mini Amarone",
        "pronunciation": "",
        "summary": "This is one of the wines that has made Allegrini famous throughout the world. The vineyard surrounds Villa della Torre, a splendid masterpiece of Renaissance architecture now owned by the family, and produces a full-bodied red wine that has an ageing potential of at least ten years. The blend is the historic combination of Corvina and Rondinella with the addition of a small quantity of Sangiovese. A small percentage of the harvested grapes are left to dry out until December and then added to the previously vinified fresh grapes",
        "varietal": ["70% Corvina Veronese", "25% Rondinella", "5% Sangiovese"],
        "primaryFlavors": ["Pepper", "Pulpy fruits", "coffee"],
        "sweetness": "Dry",
        "body": "Full Body",
        "tannin": "Medium Tannin",
        "acidity": "5.8 g/l",
        "alcohol": "13.9% ABV",
        "temp": "18°C",
        "glassType": "Large",
        "decant": "2 Hours",
        "ageability": "2 Years",
        "pairings": ["risottos", "saffron", "porcini mushrooms", "pork", "Amatriciana", "Carbonara", "lasagna", "gnocchi", "gorgonzola", "walnuts", "grilled meat", "roasts"]
    },
    {
        "name": "Alois Lageader Riff Pinot Grigio",
        "pronunciation": "A-low-ees La-Gay-der",
        "summary": "Brilliant straw-yellow color with a green tint. Fine, fruity (apples, peaches), forward varietal aromas. Pronounced, clean, elegant, grapey flavor. Light to medium-bodied with a fresh mouth-watering finish. Dry and crisp.",
        "producer": "Alois Lagedar",
        "primaryFlavors": ["green apple", "citrus fruit"],
        "varietal": ["100% Pinot Grigio"],
        "color": "white",
        "region": "Veneto, Trentino-Alto Adige, Italy",
        "pairings": ["salads", "fish", "shellfish", "pasta", "risotto", "poultry", "white meat", "mushrooms"],
        "winery": "Alois Lageder is a synonym for the highest standard of quality in viticulture and winemaking, for a sustainable, holistic corporate philosophy, and for a wide spectrum of cultural and artistic activities. Founded in 1823, and now directed by Alois Lageder, representing the fifth generation of family ownership, the winery combines tradition and innovation.",
        "history": "Ah Pinot Grigio, a zesty white wine that is as refreshing as a cold glass of lemonade on a hot summer’s day. The second most popular white wine in America, Pinot Grigio (aka Pinot Gris) is a dry white wine that has a punchy acidity. Thought to be a mutation of the red grape Pinot Noir, Pinot Gris’ skins are not green like other white grapes, but instead have a greyish blue hue, which is what gives them their name. The wine was born in Burgundy (France) but found its way to Switzerland in the 1300s, where it was considered a favorite of the Emperor. From here the grape made its way to northern Italy, and the real story of Pinot Grigio was born. In Italy, Pinot Gris became Pinot Grigio and the wine found wide success in the regions of Northeastern Italy: Lombardy, the Veneto, Friuli, Trentino and Alto Adige. From its footing in northern Italy, the wine grew to become the most popular white wine in all of Italy, and then the most popular imported white wine in the U.S."
    },
    {
        "name": "Cantine Povero –Roero Arneis",
        "summary": "This wine is straw white in colour with greenish reflections. It has an intense and fresh fragrance, with a dry and delicate flavour. Its main notes, which may depend on the year, are fresh hay, pippin apple, almond and pineapple.",
        "producer": "Cantine Povero",
        "primaryFlavors": ["melon", "almond"],
        "varietal": ["100% Arneis"],
        "color": "white",
        "region": "Roero Piedmont, Italy",
        "pairings": ["caramelized onions", "Cauliflower", "Carbonara"],
        "winery": "Tenuta Fratelli Povero owns the 'Terre del Conte' vineyard from which they obtain all the fruit necessary for the production of their Roero Arneis, a wine that now ranks among the great D.O.C.G. whites of the Italian oenological tradition. 6th generation producers, these “stewards of the earth” use little interference in the wine making process, and wines represent their truest expression of the varietal, at the will of the earth.",
        "history": "Often referred to as the “white nebbiolo“, it is most commonly found in the hills of the Roero, northwest of Alba, growing in the heart of red wine country, alongside Nebbiolo and Barbara. It is for that reason that it almost went dinosaur on us. When you have to compete for growing space with some of the heaviest hitters in all of Italian wines, and are challenging to grow, it’s a hard battle to win. Arneis owes its existence, in part, from the efforts of one winemaker, Alfredo Currado of the Vietti family, who brought it back from scarcity. Known in Piemonte to mean “little rascal“, Arneis is regarded as a somewhat difficult variety to grow but was once used to blend with Nebbiolo as a way of softening its tannic nature. Thanks to the revitalization, the grape went from 2 producers in the 1970s to multiple producers making more than 1 million gallons of the stuff today."
    },
    {
        "name": "”Fondo Malatesta” Lambrusco Sorbara",
        "pronunciation": "key-are-lee , lamb-brew-skoh, soar-bar-aw",
        "primaryFlavors": ["raspberry", "strawberry", "violets", "roses"],
        "summary": "Think bright acidity and mouth scrubbing for a dynamic spread of foods. Lambrusco Sorbara is also known locally as “Lambrusco Violletta” because the wine always smells of violets.",
        "producer": "Chiarli",
        "varietal": ["100% Lambrusco Sorbara"],
        "color": "red",
        "sparkling": "sparkling",
        "region": "Emilia Romagna, Italy",
        "history": "A family of grapes is a term used to identify grapes that are similarly named and for the most part related. More specifically speaking there is not a Lambrusco, instead many specific lambruscos, all different in what they bring to the table as far as characteristics and flavor.",
        "pairings": ["goose", "duck", "sardines", "tuna"]
    },
    {
        "name": "Corteaura Franciacorta",
        "pronunciation": "core-tee-are-a, french-a-core-tah",
        "primaryFlavors": ["white figs", "citrus fruit"],
        "summary": "The bright straw yellow color in the glass and a floral bouquet offer an intoxicating introduction. A combination of low yields, a rich creamy texture balanced with dried white fig, elegant citrus fruits, and fine bubbles.",
        "producer": "Corteaura",
        "varietal": ["100% Chardonnay"],
        "color:": "white",
        "sparkling": "sparkling",
        "region": "Lombardy, Italy",
        "pairings": ["charcuterie", "shellfish", "pork", "chicken"],
        "history": "Franciacorta is producing using the ​traditional method​ ​where secondary fermentation takes place in the individual bottles. Also known as ​méthode champagneoise​ since it’s the method Champagnes must adhere to. It’s more costly and laborious than the tank method since each bottle needs to be turned regularly."
    },
    {
        "name": "Chianti Classico",
        "pronunciation": "Key-ahn-tea class-ih-koh",
        "summary": "Well-integrated and balanced minerality, with developed tannins. On the palate, aromas of red fruits, including cherries. Bodied wine, with a pleasant, long finish. Excellent drinkability.",
        "producer": "Dievole Tuscana",
        "primaryFlavors": ["dried violets", "ripe cherry"],
        "varietal": ["90% Sangiovese", "7% Canaiolo", "3% Colorino"],
        "color": "red",
        "region": "Tuscany, Italy",
        "pairings": ["bolognese", "braised beef", "lasagna", "red sauces"],
        "winery": "Dievole, which means “Gods Will” have been producing wines since 1090. Their Chianti features classic fermentation, in large cement casks before spending 2 years in large barriques. Producing at the will of the land, there is little interference with the classic expression of the wines.",
        "history": "Chianti is easily the more recognized wine outside of Italy. It is as essential to Italian cuisine as olive oil, and synonymous with the region of Tuscany, in which the subregion of Chianti lies. Chianti will always have a base of Sangiovese, which gives it it’s firm tannin and high acidity. Within Chianti, there are eight subzones that classify the wines produced there, including Chianti Classico. The Chianti Classico is central to the region and arguably the most famous. In 1996 it was awarded DOCG(Denominazione di Origine Controllata e Garantita) status, in an effort to raise its perceived quality."
    },
    {
        "name": "La Bella Prosecco",
        "pronunciation": "pro-sek-koh",
        "summary": "Crisp and fruity, notes of green apple and ripe peaches",
        "primaryFlavors": ["green apple", "peach"],
        "varietal": ["100% Glera"],
        "color": "white",
        "sparkling": "This wine is sparkling.",
        "region": "Friuli-Venezia Giulia, Italy",
        "pairings": ["test", "no data"],
        "history": "Prosecco – the quintessential bubble of Italy! Prosecco is a sparkling white wine from north-eastern Italy, specifically the Veneto and Friuli-Venezia Giulia wine regions. It is also the informal name for the grape variety used to make these wines, which is now known officially as Glera. This green-skinned variety has been grown for hundreds of years in the Veneto and Friuli regions, most famously to produce sparkling Prosecco wines. La Bella brings a bright, fruit forward prosecco perfect on its own or in a cocktail."
    },
    {
        "name": "La Valentina Montepulciano D’Abruzzo DOC",
        "pronunciation": "Mohn-TEE-poll-CHAH-no, dah-BROOT-soh",
        "summary": "Deep ruby colour, with purple shadows. The bouquet shows rose, delicate red fruits similar to currant and raspberry, pepper, clove and accents of brush. Medium- bodied, in the mouth is velvety, with hints of plum, blueberry and licorice, with fresh and energetic tannins.",
        "producer": "La Valentina",
        "primaryFlavors": ["rose", "currant", "blueberry"],
        "varietal": ["100% Montepulciano"],
        "region": "Abruzzo",
        "pairings": ["lasagne", "lamb meat", "medium-aged cheese"],
        "winery": "After the first few years spent studying the Santa Teresa vineyard, their continuous efforts to keep improving quality and to achieve recognition for the high-quality D.O.C. wines from the Abruzzo region have become the principal goals in the company philosophy. We have learned to understand our land more fully by respecting and tending it. Each year we have had successively healthier wines of more and more authentic quality. Moved by our conviction that improvement comes only through respect for natural equilibriums, year on year we have rigorously applied our philosophy that does not permit the unrestrained use of technology and chemicals. We have decided to intervene as little as possible in what are natural processes, adhering to the concept that high-quality D.O.C. wine “has the mark of the vine on its grapes.” Convinced that a fine wine is born from the sum of so many small details, our objective must not only be to always produce fine wine, but also to make sure that our wines are always authentic.",
        "history": "The Montepulciano grape is quite prolific. The Montepulciano grape grows easily in Abruzzo. It is plump with high amounts of juice. Unlike most other varietals, this grape makes nice wine even when produced in large quantities. The grape has a deep purple and ruby color to its juice. It has lower acidity (especially for an Italian varietal) and mild sweeter tannins. The resulting wines tend to be softer and more accessible than Chianti or Nebbiolo for example. Accordingly, the young wines are nice pleasurable reds that go as well with food as without it. Heading due east from Rome lays the region of Abruzzo. This is a historically poor region whose people inhabit the hills and mountains so prevalent in the province. The hillsides are excellent for viticulture. La Valentina Farm was born on the hills overlooking Spoltore, which is near Pescara in Central Italy, in 1990. The owners, Sabatino, Roberto e Andrea Di Properzio, have been running the company since putting their development project into action in 1994."
    },
    {
        "name": "Molettieri Irpinia - Aglianico",
        "pronunciation": "alli-yawn-nico",
        "summary": "Full body, ripe cherry and dried rose aromas, spicy notes of cocoa and tobacco, firm tannins",
        "producer": "Molettieri Irpinia",
        "primaryFlavors": ["ripe cherry", "dried roses", "cocoa", "tobacco"],
        "varietal": ["100% Aglianico"],
        "color": "red",
        "region": "Campania",
        "pairings": ["braised beef", "lasagna", "bolognese", "pecorino cheese"],
        "winery": "The Azienda Vitivinicola Salvatore Molettieri was established in 1983, but viticulture and wine making have been a tradition of the family for four generations. The vineyards of the estate stand on the hills of Montemarano, one of the seventeen small towns which are part of the Taurasi DOCG appellation. This area is surrounded by mountains which offer protection against winds and hail. It is one of the best areas for the Aglianico grape variety to thrive.",
        "history": "Aglianico is a full-bodied red wine which is found almost exclusively in Southern Italy in the regions of Campania and Basilicata. Within these areas there are three production zones that have the highest tier Italian wine classification (DOCG). Each region has a decidedly different expression of the wine, but the volcanic soils are what ties them all together. Young Aglianico wines are known for strikingly savory flavors of leather, white pepper, black fruits and cured meat that when aged, develop soft dusty aromas of dried figs and sun-tanned leather."
    },
    {
        "name": "Regaleali Nero D'Avola",
        "pronunciation": "ree-gaul-lee-all-lee",
        "summary": "Bright ruby-red color, this wine offers layered notes of cherry, mulberry and raspberry. On the palate, it is complex and supple, with ripe berries flavors framed by silky tannins.",
        "producer": "Tasca Regaleali",
        "primaryFlavors": ["ripe berry"],
        "varietal": ["100% Nero D’Avola"],
        "region": "Sicily, Italy",
        "pairings": ["eggplant", "meat sauce", "meatballs", "sausages", "roasted meats"],
        "winery": "Regaleali is a vast Sicilian estate owned by the noble Tasca d'Almerita family since 1837 and best-known for its fine wines. Sicily's viticultural roots are some of the world's most ancient as the area supported vines as far back as five centuries before Christ. The Tasca D'Almerita family runs a model estate that yields approximately 200,000 cases annually.",
        "history": "The name translates to “Black [grape] of Avola,” referring to the town in Sicily where it was first identified. It’s been grown and produced for centuries. But besides local consumption, it was not widely known outside of Italy for a long time, as it was mostly exported to France to bulk out lighter red wines (they call it “le vin medicine”). It was largely ignored in the 1980’s, but has recently made a big comeback in worthy varietal releases, and is now considered the main local red grape of Sicily."
    },
    {
        "name": "Santi Chiaretto",
        "pronunciation": "key-a-ret-oh",
        "summary": "bright aromatic notes of wild cherries and strawberries, creamy texture, refreshing acidity",
        "varietal": ["65% Corvina", "30% Rondinella", "5% Molinara"],
        "primaryFlavors": ["test", "no data"],
        "color": "rosè",
        "region": "Bardolino, Italy",
        "pairings": "Salads, pasta dishes, proscuttio – Proscuitto y Rucola, Proscuitto y Funghi",
        "winery": "Bardolino Chiaretto, is one of Italy’s top rosato wine producing regions made, from the same blend of grapes that you find in Valpolicella and Amarone: Corvina, Corvinone, Rondinella and Molinara. Chiaretto’s color is a very pale pink. Chiaretto displays the primary aromas of the Corvina grape. Its fragrances range from flowers to herbaceous tones; from citrus fruits to apricots and wild berries; all accompanied by hints of spice, like cinnamon, cloves or vanilla. On the palate, Chiaretto offers youthful, mouth-watering freshness. This is a fresh, fruity and well balanced Rosè not unlike the famous roses of the Provence regions of France.",
        "history": "Rosato wines go by the name chiaretto, the “little light one,” referring to the pleasing color and lighter body of these wines compared to nearby serious reds such as Valpolicella and especially Amarone."
    },
    {
        "name": "Suavia Soave Classico",
        "pronunciation": "Suav-vee-ah",
        "summary": "On the palate it is dry, medium-bodied and smooth notes of white flowers, yellow apples, pear and a refreshing lemony zing with a pleasant long mineral finish and almond note.",
        "producer": "Suavia",
        "primaryFlavors": ["flower", "fruit"],
        "varietal": ["100% Garganega"],
        "region": "Veneto, Italy",
        "pairing": ["no data", "test"],
        "winery": "Our family, the Tessari family, has lived and worked on this land since the nineteenth century. The history of Suavia however began later, in 1982, when Giovanni and Rosetta (the father and mother), aware of the great potential of their area, decided to set up on their own and make their mark, crushing their grapes and making their own wine. The history of Suavia consists of a castle, no frog, few princes and lots of princesses. The castle is the one in Soave: a heritage from the Middle Ages, when the town was still called by the old name of Suavia; Giovanni and Rosetta’s four daughters, however, have been the main female characters in this story since the start of the twenty-first century. Today Meri, Valentina and I (Alessandra) run the winery here in Fittà, where it all started.",
        "history": "Soave is one of Italy’s most exported white wines and also one of Italy’s most important wines. Soave is Italian for “Suave“, and although many believe that the name is related to the often sleek and smooth characteristics of the wine, it actually comes the name of the Village of Soave, few kilometers East of Verona along the motorway heading to Venice, where it is produced. Garganega is the main grape varietal in Soave, DOC regulations requires 85% of the grape to be used. Wines made with Soave are some of the oldest documented in Italy, dating back to 500 B.C."
    },
    {
        "name": "Etna Rossa",
        "pronunciation": "Etna Rosa",
        "summary": "Light body, generous aromas of ripe raspberries and cranberry, black pepper and smoke, fine tannins",
        "producer": "Sciaranova and Piano Dario contradas",
        "primaryFlavors": ["raspberry", "cranberry", "black pepper", "smoke"],
        "varietal": ["100% Norella Mascalese"],
        "color": "red",
        "region": "Sicily, Italy",
        "pairings": ["roasted tomato", "pepper", "light meats", "oregano", "thyme"],
        "winery": "Mount Etna is the highest and most active volcano in Europe. Growing over the past 500,000 years and in the midst of a series of eruptions, dating as recently as December 2018. Each year, it produces enough lava to fill a 108-story skyscraper and erupts in some form almost daily. This daily activity is what allows the surrounding area to fill with nutrient rich and ever changing soil, which has sparked a huge influx in agriculture over the past decade. Etna in comparison to most of Italy, is a fairly new wine producing region but this is what makes wine from this region so magical.",
        "history": "Norello Mascalese, the main grape produced, is one of the most important indigenous volcanic grapes in the world. One of the few varietals that rivals a style similar to a Pinot Noir. Due to the nutrient rich soil of the area, you will find distinctive notes of smoky volcanic aroma, complimented with bright fruity-flower flavors such as dried cherry and tart cranberries, orange zest, and thyme. Tascante Ghiana Nera Etna Rosso is a classical wine that fully expresses its extraordinary terroir with unique sharpness."
    },
    {
        "name": "Tenute Rubino - Marmorelle Red Blend",
        "pronunciation": "Ten new tay, Mar more el lay",
        "summary": "Medium body, ethereal notes of cherry, black currants and ripened blackberry; hints of nutmeg and cocoa, well balanced",
        "producer": "Tenute Rubino",
        "primaryFlavors": ["cherry", "black currant", "ripe blackberry", "nutmeg", "cocoa"],
        "varietal": ["85% Negroamaro", "15% Melvasia Nera"],
        "region": "Puglia, Italy",
        "pairings": ["Caramelized Onions", "Bianca", "Tutta Bella", "Leonardo"],
        "winery": "Well-suited to the production of concentrated, fruity and spicy red varieties, Puglia is one of Italy’s warmest, most southerly regions. The eastern side is one long coastline bordering the Adriatic Sea, where half way down, the region becomes the Salento Peninsula. This peninsula, bordered by water on three sides, receives moist, nighttime, sea breezes that bring a welcome cooling effect to the region, and some much needed relief to the vines. Puglia, named for the Italian expression, “a pluvia,” meaning “lack of rain” becomes a challenging environment for vines to thrive.",
        "history": "Though, indigenous Primitivo, Negroamaro and Nero di Troia, all thrive in this dry climate. Negroamaro, typically blended with Malvasia nera, plays a large part in may blends made throughout the peninsula. The grape can produce wines very deep in color, as well as in taste. Wines made from Negroamaro tend to be very rustic in character, combining perfume with an earthy bitterness. This wine is a perfect fan favorite and easy drinking addition to any meal."
    },
    {
        "name": "Terredora di Paolo Falanghina",
        "pronunciation": "​tear-adore-ah d paul-oh , fal-in-geen-ah",
        "summary": "straw-yellow colour with greenish reflections. Intense and aromatic nose of green apple, pineapple and citrus. Fresh on the palate, well- balanced with a crispy acidity and a lovely, long finish",
        "producer": "Terredora Di Paolo",
        "primaryFlavors": ["pineapple", "pear"],
        "varietal": ["100% Falanghina"],
        "region": "Campania",
        "pairings": ["​soups", "fish", "buffalo mozzarella", "fresh cheeses"],
        "winery": "Terredora Di Paolo is a story of a family that is closely linked to Campania, its land, its history and its people for generations. With 494 acres of privately owned vineyards in the best sites of the Avellino province, Terredora di Paolo is one of the largest wineries in southern Italy. In Irpinian, the wines exhibit a distinctive personality due to its unique microclimate. The altitude at which the vineyards are found, the soil and the thermal fluctuations develop wines that are intense and elegant and display complex bouquets. Since its establishment in 1978, Terredora di Paolo has focused on rediscovering and restoring Campania’s ancient and native varietals such as Aglianico, Fiano, Greco and Falanghina. These varietals are key players that have brought about Campania’s wine renaissance.",
        "history": "Falanghina is a white-wine grape most likely originating in the Campania region of Italy, which is still its home (though some think it may trace it all the way back to Greece) Falanghina makes wines of substantial body and some richness. It is not notably mineral or fruit-forward; rather, it is a soft, pleasing blend of floral and honeyed (but not sweet) flavors. The flavors and acidity are, in well-made specimens, elegantly balanced. It is interesting that some descriptions have it as a notably high-acid wine, while other reviewers describe it as soft and moderate to low in acid; presumably those are simply the results of different vinification methods. Fun Fact: Falanghina may have been one of the grapes used in the renowned wine of ancient Rome, Falernian."
    },
    {
        "name": "",
        "pronunciation": "",
        "summary": "",
        "primaryFlavors": [],
        "sweetness": "",
        "body": "",
        "varietal": ["no data"],
        "tannin": "",
        "acidity": "",
        "alcohol": "",
        "temp": "",
        "glassType": "",
        "decant": "",
        "ageability": "",
        "pairings": ""
    }
];

// db.MasterWineList
//     .remove({})
//     .then(() => db.MasterWineList.collection.insertMany(wineSeed))
//     .then(data => {
//         // console.log(data.results + " records inserted!");
//
//     })
//     .catch(err => {
//         console.error(err);
//     });

module.exports = {wineSeed}